exclude:
  - "/bower_components/"
  - "bower.json"

gems: [jekyll-assets, uglifier, jekyll-admin]

assets:
  digest: true
  assets:
    - "*.js"
    - "*.css"
    - "*.jpg"
    - "*.png"
  sources:
    - assets/js
    - assets/css
    - assets/img
    - assets/bower/jquery/dist
  features:
    automatic_img_size: false
